SELECT 
COLUMN_NAME,
DATA_TYPE,
DATA_LENGTH,
CASE 
    WHEN NULLABLE = 'N' THEN
      'CAN NOT BE NULL'
    WHEN NULLABLE = 'Y' THEN
      'CAN BE NULL'
END
FROM 
user_tab_columns
WHERE TABLE_NAME = &TBL
